spring:
  application:
    name: kanflow-backend
  datasource:
    url: jdbc:postgresql://localhost:5432/kanflow
    username: postgres
    password: 12345678
  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false
    properties:
      hibernate:
        jdbc:
          time_zone: UTC
  flyway:
    enabled: true

server:
  port: ${SERVER_PORT:9090}

kanflow:
  billing:
    mock-confirmation: ${KANFLOW_BILLING_MOCK:true}
  seed-demo:
    run: ${KANFLOW_SEED_DEMO_RUN:false}

security:
  jwt:
    secret: ${JWT_SECRET:dev-only-change-me-dev-only-change-me}
    access-token-seconds: ${JWT_ACCESS_TOKEN_SECONDS:3600}

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
    tags-sorter: alpha
    operations-sorter: alpha
    doc-expansion: none
    default-models-expand-depth: 2
  show-actuator: false
