ALTER TABLE sprint_history
    ADD COLUMN cards_total INTEGER NOT NULL DEFAULT 0,
    ADD COLUMN cards_done INTEGER NOT NULL DEFAULT 0,
    ADD COLUMN checklist_total INTEGER NOT NULL DEFAULT 0,
    ADD COLUMN checklist_done INTEGER NOT NULL DEFAULT 0;
